### ISSUE TITLE
Use pytest for testing

### ISSUE THREAD

**Issue by dhimmel** [greenelab/hetmech#10]
http://doc.pytest.org/en/latest/

You can run locally with `py.test` or `pytest`.

**Comment by kkloste** [comment]
@dhimmel  -- The diffusion codes we wrote are now packaged together in the module `metapath_diffusion.py`. Should the pytest functions that test the functions in this module be included inside this module?

**Comment by dhimmel** [comment]
Let's move the tests to a new file. Currently pytest isn't detecting `test_dual_normalize` since it only looks in .py files that start or end with `test`. I'll rearrange the repo to fix these issues.

**Comment by dhimmel** [comment]
@kkloste you can now run `pytest` or `pytest hetmech` to run the tests. It's a good idea to test locally before pushing. However, Travis CI also performs the tests.

**Comment by kkloste** [comment]
Confirming, successfully ran pytests.
