### ISSUE TITLE
Caching and bulk computation of metapaths

### ISSUE THREAD

**Issue by zietzm** [greenelab/hetmech#108]
If we are doing bulk computations of metapaths, we will want to take full advantage of our developing caching functionality. During the computation of most DWPCs, the metapath will be segmented and sub-problems computed first. We do not want to cache metapaths or metapath segments that appear only once in the full list of segments. Excluding these single-appearance segments **excludes 78% of all segments** (regardless of whether looking at `max_length=4` or `max_length=5`).

Another thing to think about could be retrieval vs transpose time for some segments. For example, the first and sixth most common segments are GdD and DdG. If transposing is much slower than retrieving, maybe we want to cache both the GdD and DdG matrices. But for sparse matrices, transposing may be quite quick, in which case we would prefer storing one direction only.

I have rank-ordered all segments by their frequency of appearance. An interesting thing to note is that nearly one-third of all segments which would be included (meaning appear more than once) appear less than ten times, while only ten percent appear more than one hundred times. **Basically, the distribution of frequencies is extremely biased toward small numbers with an incredibly long tail**. The most frequent segments occur nearly 30,000 times, while only 1% occur even 1000 times. Thus, the smallest increases in performance will potentially be quite noticeable for the most frequent segments, while others may be much less visible.

**Comment by dhimmel** [comment]
I think this issue has mostly been addressed through the following pull requests:

- https://github.com/greenelab/hetmech/pull/109
- https://github.com/greenelab/hetmech/pull/111
- https://github.com/greenelab/hetmech/pull/112

One thing on the wishlist is a cache method to print stats. We can leave this issue open a bit longer in case to discuss any lingering cache issues.

**Comment by dhimmel** [comment]
Will close since we've implemented caching... although perhaps imperfectly as there seems to be a severe memory leak: https://github.com/greenelab/hetmech/issues/141.
