### ISSUE TITLE
Consider xarray for storing hetnets as multidimensional arrays

### ISSUE THREAD

**Issue by dhimmel** [greenelab/hetmech#12]
Check out the `xarray` package (https://github.com/pydata/xarray) to store hetnets as a multidimensional array.

**Comment by dhimmel** [comment]
@kkloste, the lack of row / column names in `numpy.ndarray` and `scipy.sparse` are becoming a real impediment.

I'm thinking that all user-facing functions should return `xarray.DataArray`s for this reason. We'll have to achieve the right balance where internal functions do what's efficient, while external functions return something useful (i.e. with names).

Currently, I think `diffusion.diffuse` and `degree_weight.dwwc` are the two user facing functions.

**Comment by kkloste** [comment]
That all makes sense to me.

**Comment by dhimmel** [comment]
Here's a diagram (Figure 1A from [Discovering disease-disease associations by fusing systems-level molecular data](https://doi.org/10.1038/srep03202)) that illustrates how a hetnet can be represented as an adjacency matrix for each edge type (metaedge):

![](https://cloud.githubusercontent.com/assets/1117703/24583373/9a87d656-1715-11e7-9646-7e0cc6a9f5f7.png)

Note that the Gene × Gene position has multiple adjacency matrixes. This is because there are multiple edge types that go from gene to gene.

**Comment by dhimmel** [comment]
We've exported hetnets to xarrays in [`2.xarray.ipynb`](https://github.com/greenelab/hetmech/blob/9dfb75a0920ae0240acb6efabdd806d240d265de/2.xarray.ipynb). However, due to it's lack of sparse matrix support, we haven't proceeded with using xarray. See #95 for discussion of various graph data structures. We're proceeding with our custom HetMat solution.
