### ISSUE TITLE
Add flake8 to automatically check style

### ISSUE THREAD

**Issue by dhimmel** [greenelab/hetmech#14]
See http://flake8.pycqa.org/en/latest/.

We can add it to our Travis builds.

@kkloste flake8 enforces a rather strict set of style rules. I will probably disable some which I find annoying.

**Comment by dhimmel** [comment]
Some links:

+ pep8 error codes http://pep8.readthedocs.io/en/stable/intro.html#error-codes
+ flake8 error codes https://flake8.readthedocs.io/en/2.0/warnings.html
+ `flake8 --ignore` http://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8--ignore

**Comment by kkloste** [comment]
Thanks for the links, I'll read up on this.
