### ISSUE TITLE
Fix error when importing hetmech.matrix

### ISSUE THREAD

**Issue by zietzm** [greenelab/hetmech#145]
@gwaygenomics made the following observation:

Importing `hetmech.matrix` without previously importing `hetmech.hetmat` gives an `ImportError`

In the following image, I ran the first cell, then restarted the kernel and ran only the second cell. As can be seen below, importing `hetmech.matrix` alone or before `hetmech.hetmat` gives this error.

![image](https://user-images.githubusercontent.com/7230303/47578709-159f3d00-d918-11e8-9d2a-058bb3e0efc8.png)

**Comment by gwaygenomics** [comment]
I am getting a different, but related error now when using `hetmech` in a conda environment with:

```sh
