### ISSUE TITLE
Is numpy.linalg.norm useful for the normalization step?

### ISSUE THREAD

**Issue by dhimmel** [greenelab/hetmech#15]
@kkloste I came across this function: [`numpy.linalg.norm`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html), whose doc states:

> This function is able to return one of eight different matrix norms, or one of an infinite number of vector norms (described below), depending on the value of the `ord` parameter.

Not sure whether this is helpful. Seems related to sklearn's normalize we had been using. Close this issue if it's not relevant for us.

**Comment by kkloste** [comment]
These different matrix and vector norms do not accomplish the *degree* normalization component of what we're doing. They're useful for certain normalizations, but do not accomplish what we need.
