### ISSUE TITLE
Implement Degree Weighted Path Count (DWPC)

### ISSUE THREAD

**Issue by kkloste** [greenelab/hetmech#20]
The diffusion code we have in https://github.com/greenelab/hetmech/blob/e387eee580cfe3d530a21c92df025afd9f668784/hetmech/diffusion.py
can be made to compute the DWPC for an input metapath.
Implement this functionality -- @dhimmel in which module should we put this function?

**Comment by dhimmel** [comment]
> which module should we put this function?

I think it could go in `diffusion.py`. Or you can make a new module `path_count.py`.

We will also want a basic `path_count` function that will count the number of paths without any degree normalization.

For reference, here are existing implementations of DWPC:

+ [visual](https://doi.org/10.1371/journal.pcbi.1004259.g002 "Figure 2: Heterogeneous Network Edge Prediction: A Data Integration Approach to Prioritize Disease-Associated Genes")
+ [cypher](https://thinklab.com/discussion/using-the-neo4j-graph-database-for-hetnets/112#6)
+ [python](https://github.com/dhimmel/hetio/blob/488d603dbec663b38a95ba3315d83ae4bb4a5f21/hetio/pathtools.py#L7-L15)

For now, let's ignore the issue of duplicate nodes in a path.

**Comment by kkloste** [comment]
A note for the sake of technical correctness: a path with duplicate nodes is called a "trail", and is not a "path".

**Comment by kkloste** [comment]
The current `diffusion.py` functionality already enables counting the number of walks between any source node and any target node -- simply call `diffusion.diffuse_along_metapath` with `row_damping = 0` and `column_damping = 0`.

**Comment by dhimmel** [comment]
> The current diffusion.py functionality already enables counting the number of walks between any source node and any target node

Cool. `diffusion.diffuse_along_metapath` is very flexible.

> A note for the sake of technical correctness: a path with duplicate nodes is called a "trail", and is not a "path".

So should we call what we're calculating DWWC (degree weighted walk count)?

**Comment by kkloste** [comment]
> So should we call what we're calculating DWWC (degree weighted walk count)?

I think yes, otherwise the name is misleading. It is worth noting, though, that DWWC = DWPC if the metapath does not repeat node-types.

**Comment by kkloste** [comment]
@dhimmel -- given that `diffuse_along_metapath` implements DWPC exactly in the case that no node-types are repeated, do you still want a separate function that implements DWPC in the case that there *are* repeated node-types?

**Comment by dhimmel** [comment]
I think we should change the name of the `diffuse_along_metapath` function to `dwwc_traverse` or similar (suggestions welcome).

> do you still want a separate function that implements DWPC in the case that there are repeated node-types?

That would be fanstastic, but I was under the impression that this would be a substantial engineering task. Ideally, we would exclude walks (and also probably trails) for `hetmech`. I just don't see them contributing useful information. How feasible is this? What will the computational penalty be?

**Comment by kkloste** [comment]
I agree with the name change.
We can then have some function named `diffuse` call the function `dwwc_along_metapath` with hardcoded parameter values, as you suggested.

The general task of "compute all paths" would be very expensive, but that is a much broader task than what we are considering. I feel pretty sure (but not yet 100%) that we could accomplish this with only a small constant factor penalty (3x more time, total?).

This depends on the number of times a node-type is repeated, and the number of different node-types that are repeated. In addition to the computational complexity depending on those items, the complexity of the code will also depend on those items.

**Comment by kkloste** [comment]
I just finished some analysis, and can confirm: assuming exactly one node-type gets repeated exactly one time, then we can compute the DWPC in no more than 2x the time, using only slightly more memory, compared to DWWC.

I could probably implement that (repeating no more than 1 node-type, one time) pretty soon (end of the week?).
If you want something more complicated than that, it might take me a while.

**Comment by dhimmel** [comment]
> I agree with the name change. We can then have some function named `diffuse` call the function `dwwc_along_metapath` with hardcoded parameter values, as you suggested.

Okay, after we merge #23, let's do the rename.

> assuming exactly one node-type gets repeated exactly one time, then we can compute the DWPC in no more than 2x the time, using only slightly more memory, compared to DWWC.

That's fantastic. This could revolutionize the usability of DWPCs and allow us to budget more computation for permuted networks. The single metanode duplication case will cover lot's of metapaths. A general solution would be the best, but I'm guessing that solving the easy case, will make it easier to solve the general case. Let me know if it makes sense to brainstorm before implementing this, or instead whether you should just jump right in.

**Comment by dhimmel** [comment]
FYI #28 implemented DWWC (degree-weighted walk count).
