### ISSUE TITLE
Are our adjacency matrices transposed?

### ISSUE THREAD

**Issue by dhimmel** [greenelab/hetmech#27]
Currently, our adjacency matrices for metaedges encode source nodes as columns and target nodes as rows. I'm starting to think this is backwards. Two observations:

1. to access a specific value, we must go `matrix[target_pos, source_pos]`. It's more natural to declare source then target.

2. In the proposed [DWWC implemenation](https://github.com/dhimmel/hetmech/blob/2ed28bb589caa909a85dcf979207d4dae827eb7d/hetmech/diffusion.py#L160), we have to do `dwwc_matrix = adj_mat @ dwwc_matrix` rather than `dwwc_matrix = dwwc_matrix @ adj_mat`. The later is preferable in that we could use `functools.reduce`.

@kkloste what do you think?

**Comment by dhimmel** [comment]
Following up on point 2, let's think about the following metapath: _Compound–binds–Gene–expresses–Anatomy–localizes–Disease_, with the abbreviation _CbGeAlD_.

I think a nice property is for the following chained operation to work:

`CbG @ GeA @ AlD`, where we successively dot product the adjacency matrixes.

**Comment by kkloste** [comment]
Thinking from a column-oriented perspective is merely a convention, and does not alter the output.
If it increases readability or usability, I am totally fine with switching to a row-oriented perspective.

How do you recommend proceeding with changing the implementations?
(It should be simple changes; it will just require thorough scanning of the code for all the places where things matter)

**Comment by dhimmel** [comment]
> Thinking from a column-oriented perspective is merely a convention, and does not alter the output.

Am I correct that the switch will make these dot products chainable (and this will be a highly convenient property).

> How do you recommend proceeding with changing the implementations?

Let's see what parts of #25 we want merged first. Then make these changes.

**Comment by dhimmel** [comment]
@kkloste I see that there are two ways to order ndarrays:

1. row major (C method): numpy default
2. column major (fortran method)

I wonder if this is related.

**Comment by kkloste** [comment]
Haha, yeah, the row vs column orientation debate has been waged across discipline and programming langauges for decades now.
