### ISSUE TITLE
Problem with environment installing neo4j, hetio

### ISSUE THREAD

**Issue by kkloste** [greenelab/hetmech#37]
I created the environment via conda, as per the instructions in the README, but this failed to install neo4j-driver for some reason:

![screenshot from 2017-05-22 11-46-31](https://cloud.githubusercontent.com/assets/4999436/26317212/bb87cf18-3ee4-11e7-82a5-fd748c87ae3f.png)

so I manually installed neo4j-driver via `pip install neo4j-driver`, but then discovered that `hetio` was not properly installed:
![screenshot from 2017-05-22 11-51-03](https://cloud.githubusercontent.com/assets/4999436/26317326/16ed626e-3ee5-11e7-9732-272c1e70dc5a.png)

These error messages occurred when I was definitely using the `hetmech` environment (i.e. via `source activate hetmech`, as per the README).

**Comment by dhimmel** [comment]
I'm guessing that the conda installation succeeded, but the notebook isn't running the kernel from the `hetmech` environment.

I also had some [kernel problems recently](https://github.com/jupyter/jupyter/issues/245). Can you try:

```sh
conda install --channel=conda-forge nb_conda_kernels
```

Run this inside the `hetmech` environment. Then see if you can choose the right environment in the Jupyter notebook kernel menu. If this fixes the issues, then we can add the command to `environment.yml` like [here](https://github.com/greenelab/scihub/blob/b4e09a5500b7b81cf44dddfe1b9c11955ca218dd/environment.yml#L6).

**Comment by kkloste** [comment]
I was just about to report that something fishy is going on -- apparently hetio did successfully install. I tried installing it inside the environment manually, and this happened:

```
❭ pip install hetio
Requirement already satisfied: hetio in /home/hyunil/.conda/envs/hetmech/lib/python3.6/site-packages
Requirement already satisfied: regex in /home/hyunil/.conda/envs/hetmech/lib/python3.6/site-packages (from hetio)
```

So this seems to be an error with how my jupyter notebook is running?
About to try your suggested code.

**Comment by kkloste** [comment]
Ran
> conda install --channel=conda-forge nb_conda_kernels
as suggested (inside the hetmech environment), then loaded the hetmech kernel in the notebook, and here is the output:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-871df4ccb045> in <module>()
      2 from neo4j.v1 import GraphDatabase
      3 import hetio.readwrite
----> 4 import hetio.neo4j
      5 import hetio.pathtools
      6 

/home/hyunil/.conda/envs/hetmech/lib/python3.6/site-packages/hetio/neo4j.py in <module>()
      6 from functools import reduce
      7 
----> 8 import py2neo
      9 import py2neo.packages.httpstream
     10 import pandas

ModuleNotFoundError: No module named 'py2neo'
```

**Comment by kkloste** [comment]
Ok, so I successfully installed py2neo in the environment via `pip install py2neo`, and then received

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-871df4ccb045> in <module>()
      2 from neo4j.v1 import GraphDatabase
      3 import hetio.readwrite
----> 4 import hetio.neo4j
      5 import hetio.pathtools
      6 

/home/hyunil/.conda/envs/hetmech/lib/python3.6/site-packages/hetio/neo4j.py in <module>()
      9 import py2neo.packages.httpstream
     10 import pandas
---> 11 from tqdm import tqdm
     12 
     13 import hetio.hetnet

ModuleNotFoundError: No module named 'tqdm'
```

So I successfully installed tqdm via pip, and now the first cell in the notebook works.

**Comment by kkloste** [comment]
Confirming that after those installations, the rest of the notebook runs successfully.

It seems `py2neo` and `tqdm` might need to be added to `environment.yml`,
and perhaps a note added to the README about being sure to switch the kernel in your notebook?
And then the issue seems solved, to me.

I am not knowledgeable about these details of environments and the like, so I think it'd be better if you made the necessary changes to close the issue.

**Comment by dhimmel** [comment]
> It seems py2neo and tqdm might need to be added to environment.yml

Good catch. They'[re part](https://github.com/dhimmel/hetio/blob/86c1114a2487cbcbaf05c9128d592de9ad955e49/setup.py#L72) of `extras_require` in `hetio`, but we never install them here. @kkloste I can submit a PR to add these dependencies to `environment.yml`, unless you'd like to.

**Comment by kkloste** [comment]
You go right ahead. I'll return to getting dwpc debugged.
Thanks for your help!
