### ISSUE TITLE
Hetnet permutation via adjacency matrices

### ISSUE THREAD

**Issue by dhimmel** [greenelab/hetmech#46]
In, the past, we've permuted hetnets via the hetio package. We have also [explored](https://thinklab.com/d/136) a Cypher implementation. The method we use is called XSwap as described in:

> [**Randomization Techniques for Graphs**](https://doi.org/10.1137/1.9781611972795.67)
Sami Hanhijärvi, Gemma C. Garriga, Kai Puolamäki (2009) Proceedings of the 2009 SIAM International Conference on Data Mining. doi:10.1137/1.9781611972795.67

XSwap randomly selects pairs of edges and attempts to switch the endpoints. The result is a network with degree preserved but relationships randomized. To extend this concept to hetnets, we separately permute each relationship. So I think we could implement hetnet permutation on the adjacency matrices. This may be a bit faster than the hetio implementation.

I believe this paper describes the edge swap technique for matrices:

> A Ramachandra R, Rabindranath S (1996) **A Markov Chain Monte Carlo Method for Generating Random (0, 1)-Matrices with Given Marginals**. Sankhya Indian J Stat Ser A 58: 225–242. https://www.jstor.org/stable/25051102

Anyways, @kkloste do you think there's an easy matrix implementation of XSwap?

See also (related literature):

+ [On realizations of a joint degree matrix](https://doi.org/10.1016/j.dam.2014.10.012)
+ [Construction of Directed 2K Graphs](https://arxiv.org/abs/1703.07340)
+ [Wikipedia: Degree-preserving randomization](https://en.wikipedia.org/wiki/Degree-preserving_randomization)

**Comment by kkloste** [comment]
Recording here our recent discussion online:
there is no benefit to be gained from converting a graph to a matrix for the purposes of this edge swapping operation

**Comment by dhimmel** [comment]
> there is no benefit to be gained from converting a graph to a matrix for the purposes of this edge swapping operation

Good to know. Will close this issue.
