### ISSUE TITLE
two-repeated-nodes can be deleted

### ISSUE THREAD

**Issue by kkloste** [greenelab/hetmech#50]
I'm still figuring out how to handle multiple forks, branches, setting upstream, etc.
The branch two-repeated-nodes was intended to live on my fork, not here.

I've got all the changes in kkloste:multi-duplicate, so greenlab:two-repeated-nodes can be deleted
@dhimmel

**Comment by dhimmel** [comment]
@kkloste you're talking about [the branch](https://github.com/greenelab/hetmech/tree/two-repeated-nodes)?

**Comment by kkloste** [comment]
@dhimmel Yep!

**Comment by dhimmel** [comment]
@kkloste deleted `two-repeated-nodes`. Can the `dwpc` [branch](https://github.com/greenelab/hetmech/tree/dwpc) go as well?

**Comment by dhimmel** [comment]
@kkloste I deleted `dwpc` (thought you had responded yep) Sorry if that causes issue. I don't think it had any recent code.

**Comment by kkloste** [comment]
No, that's fine
