### ISSUE TITLE
Disk storage of DWPC matrices

### ISSUE THREAD

**Issue by zietzm** [greenelab/hetmech#76]
Refs #74 

We would like to cache the DWPC matrices on disk, with the ability to rapidly read them. I looked into several different storage methods. HDF5 has a nice Python (somewhat) wrapper called [PyTables](http://www.pytables.org/), which seems useful. In addition, there is a [native Numpy/Scipy saving format,](https://docs.scipy.org/doc/numpy/neps/npy-format.html) .npy/.npz. In a quick notebook example I did earlier today, these two methods seem to read back matrices at comparable speeds (~4.3 ms). With this in mind, I will do some more rigorous speed tests in the next few days, and I will use this issue to organize updates.

**Comment by dhimmel** [comment]
Nice!

> these two methods seem to read back matrices at comparable speeds (~4.3 ms)

That's 233 matrii per second. Not bad. Now what dimension was this matrix? I assume a GxG matrix will take a double-order of mag longer to read in than a DxD.

Some other considerations:

+ we will want to store information on node identity, such as a dataframe of their identifiers and names.  This doesn't necessarily need to be part of the matrix data store, but with HDF5 it could be?

+ [memory-mapping](https://docs.scipy.org/doc/numpy/reference/generated/numpy.memmap.html) could be a big plus in some cases. For example, if someone provides 0-weight for most seed nodes, we don't actually have to read most rows of the matrix (only the rows with nonzero seed weights). How good will each format be for either memory-mapped, subsetted, or piecewise reading?

**Comment by dhimmel** [comment]
See https://github.com/greenelab/hetmech/pull/78 which compares different serialization methods. After this is merged, I think the next step will to get some estimates of total disk space required were we to save everything as `.npy` matrices.

For this we will need to compute the following sets of metapaths for Hetionet v1.0:

1. All metapaths <= length 1
2. All metapaths <= length 2
3. All metapaths <= length 3

and so on, perhaps up to five. Note that currently hetio does not have this feature builtin, although we could add it.

Then we will need to compute the dimensionality of each DWPC matrix and how much disk space it will take up. One optimization may be to log1p the DWPC values allowing us to get by with serializing with a dtype that takes less bytes. @kkloste any insights regarding efficiency saving matrices that consist of small floating point values (usually < 0.01)?

Then we will need to see the total disk space required to store all metapaths for a given length cutoff. Then I think we'll know whether this approach is feasible.

**Comment by zietzm** [comment]
I'd be happy to work on this. Now that the hetio PR is merged, I will make a notebook to explore the approximate size of storing these matrices. I'm not sure about the theoretical side of log1p to save space, but I can experiment and find how much space is required one way or the other.

**Comment by dhimmel** [comment]
> I will make a notebook to explore the approximate size of storing these matrices.

Awesome! Let's also edit the existing notebook in explore to investigate the following, as per discussion in https://github.com/numpy/numpy/issues/10852#issuecomment-379310284:

>  I don't think we tested whether doing "scipy.sparse @ memmap" acheives the same efficiency as the subset method. @zietzm let's see what happens to the runtime in the non-subsetted multiplication if we make vector a scipy.sparse matrix.
