### ISSUE TITLE
Add pqtl_entrez_id column to pqtl.tsv

### ISSUE THREAD

**Issue by dhimmel** [greenelab/hetmech#82]
Follows up on https://github.com/greenelab/hetmech/pull/81 by @naglem.

IIRC, some of the in-progress versions of `pqtl.tsv` from https://github.com/greenelab/hetmech/pull/81 had a column titled `pqtl_entrez_id`, which had the genes from `pqtl_gene`, but converted to entrez GeneIDs. It looks like this didn't make it into the merged [`pqtl.tsv`](https://github.com/greenelab/hetmech/blob/e3dd5cdc2b97f235d914d43bf39ff7e41965e482/data/pqtl/pqtl.tsv)

@naglem would you be able to re-add the `pqtl_entrez_id` column? Would make the analysis a tad bit easier.

**Comment by naglem** [comment]
@dhimmel I've updated the data in `data/pqtl/pqtl.tsv` to have a entrez ID column labeled `pqtl_entrez_id`. Let me know if you have any issues with this, thanks.

**Comment by dhimmel** [comment]
Awesome! We'll need to merge these changes in via a pull request. I created https://github.com/greenelab/hetmech/pull/84, but things have gotten a bit messed up since you haven't been creating new branches for each pull request. [Here's a guide](https://github.com/cognoma/cognoma/blob/master/CONTRIBUTING.md#contribution-workflow) on the general pull request workflow. The key is to keep your master branch up to date with `upstream/master` and to start the pull requests from an up-to-date branch. Note that when we merge PRs, we often squash merge so the actual commits end up getting combined into one. This means it's crucial to always pull the commits from `upstream/master`. 

If you create an up-to-date branch, you should be able to apply the single commit that should form the pull request by running:

```
git cherry-pick e65dd8d0e3c434369c442c73415d05ba495d4791
```

**Comment by naglem** [comment]
Hi @dhimmel, not sure if I resolved this, but i created a new branch for this pull request, when I apply the command `git cherry-pick e65dd8d0e3c434369c442c73415d05ba495d4791` it indicates that the branch is up to date, with nothing to commit. Again not sure if it is resolved.

**Comment by dhimmel** [comment]
You will know that things are correct if when you do `git log` you see e65dd8d0e3c434369c442c73415d05ba495d4791 is the most recent commit followed by e3dd5cdc2b97f235d914d43bf39ff7e41965e482.

That's good you know have a branch besides master. Now this is what I think you'll have to do:

```
# get back to master
git checkout master

# return master branch to a previous state
git reset --hard c34d8d94a072418a97ebd14d86412a78fbe17c03

# Add greenelab/hetmech repo as `upstream` repo
git remote add upstream https://github.com/greenelab/hetmech.git

# Fast forward master branch to upstream
git pull --ff-only upstream master

# Checkout new branch for this PR
git checkout -b issue-62

# Add the commit
git cherry-pick e65dd8d0e3c434369c442c73415d05ba495d4791

# Push to GitHub (it will have an error, copy the suggested command to set the remote branch)
git push

# Go to github and create PR.
```

Let's see if that works

**Comment by naglem** [comment]
@dhimmel  [`e65dd8d`](https://github.com/greenelab/hetmech/commit/e65dd8d0e3c434369c442c73415d05ba495d4791) is the most recent commit, but it is followed by [`fb657bd`](https://github.com/greenelab/hetmech/commit/fb657bd810212e6b039648b86c8b40bc246fcdec). When I git cherry-pick, it says: 

> On branch issue-62 
You are currently cherry-picking commit e65dd8d.
> nothing to commit, working tree clean
> The previous cherry-pick is now empty, possibly due to conflict resolution.
> If you wish to commit it anyway, use:
>     `git commit --allow-empty`
> Otherwise, please use 'git reset'

Should I perform `git commit --allow-empty`?

**Comment by dhimmel** [comment]
Hmm. Did all of the previous commands work, or did some appear to result in errors? `git remote add` will error if its already been configured (that's fine). I'm not sure why you are still seeing https://github.com/greenelab/hetmech/commit/fb657bd810212e6b039648b86c8b40bc246fcdec in your history because the `git reset --hard` should have removed that.

**Comment by naglem** [comment]
When I perform `git pull --ff-only upstream master`, I get:
>From github.com:naglem/hetmech
> * branch            master     -> FETCH_HEAD
>Updating c34d8d9..e65dd8d
>Fast-forward
> data/pqtl/README.md               |      3 +
> data/pqtl/pqtl.tsv                |   2558 +++
> data/pqtl/snps-to-locus-genes.tsv | 131466 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
> environment.yml                   |      1 +
> 4 files changed, 134028 insertions(+)
> create mode 100644 data/pqtl/README.md
> create mode 100644 data/pqtl/pqtl.tsv
> create mode 100644 data/pqtl/snps-to-locus-genes.tsv
Is this correct? The other commands work...

**Comment by dhimmel** [comment]
Yes, the git pull looks good. `--ff-only` stands for fast forward only and ensures that there are no commits in the local branch that aren't in the remote branch you're pulling from. In other words, you cannot have a divergence.

Since the cherry-pick seems that it may not be working, can you create a new branch and just replace the pqtl.tsv with the correct version (i.e. [this one](https://github.com/naglem/hetmech/raw/e65dd8d0e3c434369c442c73415d05ba495d4791/data/pqtl/pqtl.tsv)). Then add that file and commit it?

**Comment by naglem** [comment]
I closed the last PR. It seems that when I perform `git pull --ff-only upstream master`, it pulls all commit history into the current branch, including the commits that I made. When I do a hard reset, the git log indicates that I am back to that commit, so it must be related to the `git pull` command.

**Comment by dhimmel** [comment]
What does `git remote --verbose` output? It sounds like you may have `upstream` configured to point at `naglem/hetmech` rather than `greenelab/hetmech`.

**Comment by naglem** [comment]
@dhimmel I think this was the issue, I reset the upstream branch, and now it appears to be correct when I do the PR. Let me know if you see other issues. Thanks for the help!

**Comment by dhimmel** [comment]
Nice. Here are the steps to avoid this from happening in future. Now that the PR has been merged you can go:

```
# Return to your master branch
git checkout master

# Fast forward master branch to upstream
git pull --ff-only upstream master

# Update master branch on your github
git push origin master
```

It's a good idea to do the `git pull` command right before you start a new PR to make sure you're working from the latest upstream version. Before making any commits for a new feature / PR, make sure to checkout a new branch. This way your master will always be behind or in line with the upstream.
