### ISSUE TITLE
Using hetmech outside repository

### ISSUE THREAD

**Issue by gwaygenomics** [greenelab/hetmech#88]
Hi @dhimmel - thanks for putting this repo and analysis together.

I am looking to repurpose [8.gene-set-search.ipynb](https://github.com/greenelab/hetmech/blob/master/8.gene-set-search.ipynb) for alternative analyses. This script requires methods written in scripts inside the `hetmech` folder. How would you recommend using these methods?

For instance,

```python
from hetmech.degree_weight import dwpc
from hetmech.matrix import get_node_to_position
```

fails anywhere outside of this repository.

**Comment by zietzm** [comment]
@gwaygenomics could this be done as simply as adding a `setup.py` file that allows you to import the git repo with ‘pip install -e {hetmech}`?

**Comment by cgreene** [comment]
Does this require a `__init__.py`?

**Comment by gwaygenomics** [comment]
Thanks @zietzm ! I am interested in using these methods in whichever way is best/easiest. I was wondering if you guys have already found a solution to this or if we should work together to build one

**Comment by zietzm** [comment]
@gwaygenomics I added a quick PR #89 which would add a minimal `setup.py` file. I'm unfortunately not too familiar with the specifics of install requirements in pip, so perhaps this could be solved in a more elegant way. 

We use a conda environment for the Hetmech in general, but I think the requirements [in the file](https://github.com/greenelab/hetmech/pull/89/files) cover what all the necessary `.py` files need. Are you familiar with any way we could link the requirements pip wants to see with the conda environment in [`environment.yml`](https://github.com/greenelab/hetmech/blob/master/environment.yml)?

Either way, I can push this to a new branch, "setup", for the time being, which you could install using:
`pip install -e git://github.com/greenelab/hetmech.git@setup#egg=hetmech`

**Comment by dhimmel** [comment]
I agree that it'd be nice to be able to import this codebase elsewhere. However, no guarantees this repo continuous to be where the code is hosted. So note your version of the repo when installing hetmech elsewhere.

For environment.yml of an external project that import hetmech, you can do something like:

```
  - pip:
    - git+https://github.com/greenelab/hetmech@fdcf40b4771237a24b73a91446e6e04dded97455
```

**Comment by dhimmel** [comment]
> Does this require a `__init__.py`?

We already have [one](https://github.com/greenelab/hetmech/blob/master/hetmech/__init__.py), so we should be good there.

**Comment by gwaygenomics** [comment]
Thanks @dhimmel and @zietzm ! I can confirm that adding:

```bash
- pip:
  - git+https://github.com/greenelab/hetmech@523d22df9e6069948ca82e6046c4c0c769408a92 
```

to my environment worked well.
