### ISSUE TITLE
Alternative graph data structures

### ISSUE THREAD

**Issue by zietzm** [greenelab/hetmech#95]
We are considering creating another base representation of hetnets. One of the main goals is to facilitate faster network loading, which at present can take over a minute and a half to load a graph. 

The following are under consideration:
* [Mambo](https://github.com/snap-stanford/mambo), which relies on [SNAP](https://snap.stanford.edu/snappy/). 
* [GraphFrames](https://graphframes.github.io/index.html), a graph package for Apache Spark. Advantages of this framework are that metadata and multiple edge types are supported in a logical way, Spark scales well in case we eventually make hetmech a back-end server application, and the data structure is highly-used. However, we would have to re-implement the DWPC in a way that either computes exact path-level results (path and corresponding DWPC) more slowly than the current matrix implementation or computes path-level DWPC only.
* HetMat, what would be an internally-produced matrix-first representation of the network. This option would allow us to store the entire Hetionet-v1.0 and five permutations in about 30 MB as scipy sparse matrices in `.npz` format. Moreover, unlike the other methods, we would likely not have to change more than a few functions in order to load on-disk adjacency matrices.

**Comment by dhimmel** [comment]
The following products are related and may be good for storing dataframes and potentially matrices on disk:

- https://github.com/wesm/feather
- https://github.com/apache/arrow
- https://parquet.apache.org/

**Comment by zietzm** [comment]
Closed by #97

**Comment by dhimmel** [comment]
I recently came across `multinetx` ([GitHub](https://github.com/nkoub/multinetx)), which is a:

> python package for the manipulation and visualization of multilayer networks. The core of this package is a MultilayerGraph, a class that inherits all properties from networkx.Graph().

I don't think we have any use for this package at the moment, but I wanted to note it here, so we can keep an eye on its development.
